MANAGER_SERVER_DNS_ADDRESS = "vault-manager"
SETUP_MASTER_DNS_ADDRESS = MANAGER_SERVER_DNS_ADDRESS

# TODO: make eouter env vars
MANAGER_SERVER_PORT = 5000
BOOTSTRAP_SERVER_PORT = 5000
SHARE_SERVER_PORT = 5000
SETUP_MASTER_SERVICE_PORT = 4000
SETUP_UNIT_SERVICE_PORT = 4000


DOCKER_IMAGE_NAME = "vault"
DOCKER_SHARE_SERVER_COMMAND = "python -m src.vault.share_server"
DOCKER_BOOTSTRAP_SERVER_COMMAND = "python -m src.vault.bootstrap"
DOCKER_NETWORK_NAME = "vault-net"

DB_DNS_ADDRESS = "vault-postgres"
DB_PORT = 5432
DB_USERNAME = "user"
DB_PASSWORD = "pass"
DB_NAME = "proddb"
DB_URL = f"postgresql+asyncpg://{DB_USERNAME}:{DB_PASSWORD}@{DB_DNS_ADDRESS}:{DB_PORT}/{DB_NAME}"

MANAGER_NUM_SHARE_SERVERS = 2
