name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Setup uv
        uses: astral-sh/setup-uv@v1
        with:
          enable-cache: true
          version: "0.8.11"

      - name: Run tests
        run: uv run pytest tests

      - name: Build docs
        if: github.event_name == 'pull_request'
        run: uv run --group docs mkdocs build

      - name: Install deps for WeasyPrint
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          apt update
          apt install -y \
            libcairo2 libpango-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info

      - name: Upload docs
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          ENABLE_PDF_EXPORT: 1
        run: uv run --group docs mkdocs gh-deploy --force
